// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AgentPermissionDecision(arg1:string,arg2:boolean):Promise<void>;

export function AgentSend(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<void>;

export function AgentStart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>):Promise<void>;

export function AgentStop(arg1:string):Promise<void>;

export function CreateWindowSession(arg1:string):Promise<main.WindowSession>;

export function DeleteAgentHistory(arg1:string):Promise<void>;

export function DeleteProviderKey(arg1:string):Promise<void>;

export function DeleteWindowSession(arg1:string):Promise<void>;

export function GetClipboardImage():Promise<string>;

export function GetEffectiveConfig():Promise<main.EffectiveConfig>;

export function GetGlobalConfig():Promise<main.GlobalConfig>;

export function GetHomeDir():Promise<string>;

export function GetSessionID(arg1:string):Promise<string>;

export function HasProviderKey(arg1:string):Promise<boolean>;

export function ListClaudeSessions():Promise<Array<main.StoredSession>>;

export function ListDirectory(arg1:string):Promise<Array<main.FileEntry>>;

export function ListProviderModels(arg1:string):Promise<Array<main.ModelInfo>>;

export function ListWindowSessions():Promise<Array<main.WindowSessionSummary>>;

export function LoadAgentSessionHistory(arg1:string):Promise<Array<main.HistoryMessage>>;

export function LoadSessionHistory(arg1:string,arg2:string):Promise<Array<main.HistoryMessage>>;

export function LoadWindowSession(arg1:string):Promise<main.WindowSession>;

export function Log(arg1:string):Promise<void>;

export function NewWindow():Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function PlaySound(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RunGitDiff(arg1:string):Promise<string>;

export function SaveGlobalConfig(arg1:main.GlobalConfig):Promise<void>;

export function SaveWindowSession(arg1:main.WindowSession):Promise<void>;

export function SessionResume(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SessionSend(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SessionStart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SessionStop(arg1:string):Promise<void>;

export function SetProviderKey(arg1:string,arg2:string):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function TerminalDeleteScrollback(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalLoadScrollback(arg1:string):Promise<string>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalSaveScrollback(arg1:string,arg2:string):Promise<void>;

export function TerminalStart(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function TerminalStop(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
