// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateWindowSession(arg1) {
  return window['go']['main']['App']['CreateWindowSession'](arg1);
}

export function DeleteWindowSession(arg1) {
  return window['go']['main']['App']['DeleteWindowSession'](arg1);
}

export function GetEffectiveConfig() {
  return window['go']['main']['App']['GetEffectiveConfig']();
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetSessionID(arg1) {
  return window['go']['main']['App']['GetSessionID'](arg1);
}

export function ListClaudeSessions() {
  return window['go']['main']['App']['ListClaudeSessions']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListWindowSessions() {
  return window['go']['main']['App']['ListWindowSessions']();
}

export function LoadSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadSessionHistory'](arg1, arg2);
}

export function LoadWindowSession(arg1) {
  return window['go']['main']['App']['LoadWindowSession'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PlaySound(arg1) {
  return window['go']['main']['App']['PlaySound'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RunGitDiff(arg1) {
  return window['go']['main']['App']['RunGitDiff'](arg1);
}

export function SaveGlobalConfig(arg1) {
  return window['go']['main']['App']['SaveGlobalConfig'](arg1);
}

export function SaveWindowSession(arg1) {
  return window['go']['main']['App']['SaveWindowSession'](arg1);
}

export function SessionResume(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SessionResume'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SessionSend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SessionSend'](arg1, arg2, arg3, arg4);
}

export function SessionStart(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SessionStart'](arg1, arg2, arg3, arg4, arg5);
}

export function SessionStop(arg1) {
  return window['go']['main']['App']['SessionStop'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function TerminalDeleteScrollback(arg1) {
  return window['go']['main']['App']['TerminalDeleteScrollback'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalLoadScrollback(arg1) {
  return window['go']['main']['App']['TerminalLoadScrollback'](arg1);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalSaveScrollback(arg1, arg2) {
  return window['go']['main']['App']['TerminalSaveScrollback'](arg1, arg2);
}

export function TerminalStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TerminalStart'](arg1, arg2, arg3, arg4);
}

export function TerminalStop(arg1) {
  return window['go']['main']['App']['TerminalStop'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
