// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function GetHomeDir():Promise<string>;

export function GetProjectName():Promise<string>;


export function GetSessionID(arg1:string):Promise<string>;

export function ListClaudeSessions():Promise<Array<main.StoredSession>>;

export function LoadSessionHistory(arg1:string,arg2:string):Promise<Array<main.HistoryMessage>>;

export function Log(arg1:string):Promise<void>;

export function NewWindow():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SaveTabConfigs(arg1:Array<main.TabConfig>):Promise<void>;

export function RunGitDiff(arg1:string):Promise<string>;

export function SessionResume(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function SessionSend(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SessionStart(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SessionStop(arg1:string):Promise<void>;

export function SetProjectName(arg1:string):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function TerminalStart(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function TerminalStop(arg1:string):Promise<void>;
