// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetProjectName() {
  return window['go']['main']['App']['GetProjectName']();
}

export function GetSessionID(arg1) {
  return window['go']['main']['App']['GetSessionID'](arg1);
}

export function ListClaudeSessions() {
  return window['go']['main']['App']['ListClaudeSessions']();
}

export function LoadSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadSessionHistory'](arg1, arg2);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function NewWindow() {
  return window['go']['main']['App']['NewWindow']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveTabConfigs(arg1) {
  return window['go']['main']['App']['SaveTabConfigs'](arg1);
}

export function RunGitDiff(arg1) {
  return window['go']['main']['App']['RunGitDiff'](arg1);
}

export function SessionResume(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SessionResume'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SessionSend(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SessionSend'](arg1, arg2, arg3, arg4);
}

export function SessionStart(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SessionStart'](arg1, arg2, arg3, arg4, arg5);
}

export function SessionStop(arg1) {
  return window['go']['main']['App']['SessionStop'](arg1);
}

export function SetProjectName(arg1) {
  return window['go']['main']['App']['SetProjectName'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function TerminalStart(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TerminalStart'](arg1, arg2, arg3, arg4);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function TerminalStop(arg1) {
  return window['go']['main']['App']['TerminalStop'](arg1);
}
